disabled_rules:
  - cyclomatic_complexity
  - identifier_name
  - inclusive_language
  - multiple_closures_with_trailing_closure
  - redundant_string_enum_value
  - type_name
  - vertical_parameter_alignment

opt_in_rules:
  # - accessibility_label_for_image # TODO: enable later
  # - accessibility_trait_for_button # TODO: enable later
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  # - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  # - explicit_init
  - extension_access_modifier
  # - fatal_error_message
  # - file_name
  - file_name_no_space
  # - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  # - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  # - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  # - number_separator
  - operator_usage_whitespace
  # - overridden_super_call
  - prefer_self_type_over_type_of_self
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  # - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  # - vertical_parameter_alignment_on_call
  # - vertical_whitespace_closing_braces
  # - vertical_whitespace_opening_braces
  # - weak_delegate
  - yoda_condition

analyzer_rules:
  - typesafe_array_init
  - unused_declaration
  - unused_import

line_length:
  warning: 180
  error: 220

file_length:
  warning: 500
  error: 700

closure_body_length:
  warning: 60
  error: 80

function_body_length:
  warning: 60
  error: 80

nesting:
  type_level: 3
  function_level: 2

switch_case_alignment:
  indented_cases: false

force_cast: error

force_try: error

custom_rules:
  tabs_not_spaces:
    name: "Tabs"
    regex: "^ {2,4}"
    message: "Use tabs, not spaces"
