//
//  Localization.swift
//  Harbour
//
//  Created by royal on 02/10/2021.
//

import Foundation

enum Localization: String {
	case SETTINGS_PERSIST_ATTACHED_CONTAINER_TITLE = "%SETTINGS_PERSIST_ATTACHED_CONTAINER_TITLE%"
	case SETTINGS_PERSIST_ATTACHED_CONTAINER_DESCRIPTION = "%SETTINGS_PERSIST_ATTACHED_CONTAINER_DESCRIPTION%"
	case SETTINGS_BACKGROUND_REFRESH_TITLE = "%SETTINGS_BACKGROUND_REFRESH_TITLE%"
	case SETTINGS_BACKGROUND_REFRESH_DESCRIPTION = "%SETTINGS_BACKGROUND_REFRESH_DESCRIPTION%"
	case SETTINGS_AUTO_REFRESH_TITLE = "%SETTINGS_AUTO_REFRESH_TITLE%"
	
	case SETTINGS_ENABLE_HAPTICS_TITLE = "%SETTINGS_ENABLE_HAPTICS_TITLE%"
	case SETTINGS_ENABLE_HAPTICS_DESCRIPTION = "%SETTINGS_ENABLE_HAPTICS_DESCRIPTION%"
	
	case SETTINGS_CL_USE_GRID_VIEW_TITLE = "%SETTINGS_CL_USE_GRID_VIEW_TITLE%"
	case SETTINGS_CL_USE_GRID_VIEW_DESCRIPTION = "%SETTINGS_CL_USE_GRID_VIEW_DESCRIPTION%"
	case SETTINGS_CL_USE_COLUMNS_TITLE = "%SETTINGS_CL_USE_COLUMNS_TITLE%"
	case SETTINGS_CL_USE_COLUMNS_DESCRIPTION = "%SETTINGS_CL_USE_COLUMNS_DESCRIPTION%"
	case SETTINGS_CL_USE_COLORED_CONTAINER_CELLS_TITLE = "%SETTINGS_CL_USE_COLORED_CONTAINER_CELLS_TITLE%"
	case SETTINGS_CL_USE_COLORED_CONTAINER_CELLS_DESCRIPTION = "%SETTINGS_CL_USE_COLORED_CONTAINER_CELLS_DESCRIPTION%"
	
	case SETTINGS_FOOTER = "%SETTINGS_FOOTER%"
	
	case SETUP_FEATURE1_TITLE = "%SETUP_FEATURE1_TITLE%"
	case SETUP_FEATURE1_DESCRIPTION = "%SETUP_FEATURE1_DESCRIPTION%"
	case SETUP_FEATURE2_TITLE = "%SETUP_FEATURE2_TITLE%"
	case SETUP_FEATURE2_DESCRIPTION = "%SETUP_FEATURE2_DESCRIPTION%"
	case SETUP_FEATURE3_TITLE = "%SETUP_FEATURE3_TITLE%"
	case SETUP_FEATURE3_DESCRIPTION = "%SETUP_FEATURE3_DESCRIPTION%"
	
	case CONTAINER_DISMISSED_INDICATOR_TITLE = "%CONTAINER_DISMISSED_INDICATOR_TITLE%"
	case CONTAINER_DISMISSED_INDICATOR_DESCRIPTION = "%CONTAINER_DISMISSED_INDICATOR_DESCRIPTION%"
	
	case WEBSOCKET_DISCONNECTED_TITLE = "%WEBSOCKET_DISCONNECTED_TITLE%"
	
	case KEYCHAIN_TOKEN_COMMENT = "%KEYCHAIN_TOKEN_COMMENT%"
	case KEYCHAIN_CREDS_COMMENT = "%KEYCHAIN_CREDS_COMMENT%"
	
	case WIDGET_STATUS_NAME = "%WIDGET_STATUS_NAME%"
	case WIDGET_STATUS_DESCRIPTION = "%WIDGET_STATUS_DESCRIPTION%"
	
	case PORTAINERERROR_NO_SERVER = "%PORTAINERERROR_NO_SERVER%"
	case PORTAINERERROR_NO_API = "%PORTAINERERROR_NO_API%"
	case PORTAINERERROR_NO_ENDPOINT = "%PORTAINERERROR_NO_ENDPOINT%"
	case PORTAINERERROR_NO_TOKEN = "%PORTAINERERROR_NO_TOKEN%"
	case PORTAINERERROR_NO_CREDENTIALS = "%PORTAINERERROR_NO_CREDENTIALS%"
	
	var localized: String { NSLocalizedString(self.rawValue, comment: "") }
}
