//
//  Localization.swift
//  Harbour
//
//  Created by unitears on 02/10/2021.
//

enum Localization {
	static var CONTAINER_DISMISSED_NOTIFICATION_TITLE = "%CONTAINER_DISMISSED_NOTIFICATION_TITLE%"
	static var CONTAINER_DISMISSED_NOTIFICATION_DESCRIPTION = "%CONTAINER_DISMISSED_NOTIFICATION_DESCRIPTION%"
	
	static var SETTINGS_PERSIST_ATTACHED_CONTAINER_TITLE = "%SETTINGS_PERSIST_ATTACHED_CONTAINER_TITLE%"
	static var SETTINGS_PERSIST_ATTACHED_CONTAINER_DESCRIPTION = "%SETTINGS_PERSIST_ATTACHED_CONTAINER_DESCRIPTION%"
	static var SETTINGS_CONTAINER_DISCONNECTED_PROMPT_TITLE = "%SETTINGS_CONTAINER_DISCONNECTED_PROMPT_TITLE%"
	static var SETTINGS_CONTAINER_DISCONNECTED_PROMPT_DESCRIPTION = "%SETTINGS_CONTAINER_DISCONNECTED_PROMPT_DESCRIPTION%"
	static var SETTINGS_ENABLE_HAPTICS_TITLE = "%SETTINGS_ENABLE_HAPTICS_TITLE%"
	static var SETTINGS_ENABLE_HAPTICS_DESCRIPTION = "%SETTINGS_ENABLE_HAPTICS_DESCRIPTION%"
	static var SETTINGS_AUTO_REFRESH_TITLE = "%SETTINGS_AUTO_REFRESH_TITLE%"
	
	static var SETUP_FEATURE1_TITLE = "%SETUP_FEATURE1_TITLE%"
	static var SETUP_FEATURE1_DESCRIPTION = "%SETUP_FEATURE1_DESCRIPTION%"
	static var SETUP_FEATURE2_TITLE = "%SETUP_FEATURE2_TITLE%"
	static var SETUP_FEATURE2_DESCRIPTION = "%SETUP_FEATURE2_DESCRIPTION%"
	static var SETUP_FEATURE3_TITLE = "%SETUP_FEATURE3_TITLE%"
	static var SETUP_FEATURE3_DESCRIPTION = "%SETUP_FEATURE3_DESCRIPTION%"
}
